### ISSUE TITLE
Improve styling sections for each visual element with CSS selectors

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-doc#1113]
**Description**
Add CSS selectors that will help users style their visual elements. This documentation section could be generated with Taipy.

For example, navbar:
```css
.taipy-navbar .MuiButtonBase-root {
  text-transform: unset;
}

/*add more*/
```

Selector:

```css
.taipy-selector{
    margin:0px !important;
}

/* inside of selector */
.taipy-selector .MuiInputBase-root{
    background-color: #572c5f38;
    color: #221025;
    border-radius: 0px;
    height: 50px;
}

/* label of selector */
.taipy-selector .MuiFormLabel-root{
    color: #572c5f;
}
```

Input:

```css
/* inside of input */
.taipy-input .MuiInputBase-root{
    background-color: #572c5f38;
    color: #221025;
    border-radius: 0px;
    height: 50px;
}

/* label of input */
.taipy-input .MuiFormLabel-root{
    color: #ce0707;
}

```

Table:

```css
/* Table Head (apply to every child) */
.taipy-table .MuiTableHead-root .MuiTableRow-root>* {
    background-color: #b49cb9;
    color: #221025 !important;
    width: max-content;
}

/* Table Body - rows (apply to every child) */
.taipy-table .MuiTable-root {
    background-color: #572c5f0b;
    color: #221025;
}

/* Table Pagination/Footer  */
.taipy-table .MuiTablePagination-root{
    background-color: #572c5f38 !important;
    color: #221025 !important;
}

```
